alias ls="eza --icons=always --no-user -ag"
alias ll="ls -lah"
alias l="ls -lah"
alias cat="bat -p"
alias wshow-pic="wezterm imgcat"
alias kshow-pic="kitten icat"
alias tree="eza --tree --ignore-glob .git"
alias ga="git add"
alias gc="git commit"
alias gp="git push"
alias gst="git status"
alias gdiff="git difftool --no-symlinks --dir-diff"
alias vide="neovide"
alias cls="clear"
